# Generated by Django 3.1.1 on 2020-10-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Отчество'),
        ),
    ]
