# Generated by Django 3.0.4 on 2020-03-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200307_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.CharField(max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='parent',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='parent',
            name='gender',
            field=models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=7, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='parent',
            name='patronymic',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='parent',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=7, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=7, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Телефон'),
        ),
    ]
