# Generated by Django 3.0.4 on 2020-03-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200307_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='worktime',
            field=models.TimeField(blank=True, null=True, verbose_name='Время работы'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ElemOfTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateField(verbose_name='Время начала')),
                ('end_time', models.DateField(verbose_name='Время конца')),
                ('day', models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], max_length=2, verbose_name='День')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Timetable')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='union',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Union', verbose_name='Объединение'),
        ),
    ]
