# Generated by Django 3.0.4 on 2020-04-03 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0004_auto_20200307_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAttend', models.BooleanField(default=False, verbose_name='Посетил')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
                ('link', models.ImageField(upload_to='logo', verbose_name='Иконка')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('cancelReason', models.CharField(default=None, max_length=128, null=True, verbose_name='Причина отмены')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginTime', models.TimeField(verbose_name='Время начала')),
                ('day', models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота')], max_length=2, verbose_name='День')),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='groups',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('has_groups', 'Имеет группы'), ('edit_any_studySession', 'Редактирует любые занятия'), ('cancel_studySession', 'Отменяет занятия')]},
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Педагог'),
        ),
        migrations.AddField(
            model_name='student',
            name='isDeleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='union',
            name='occupationReason',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Причина занятости'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='gender',
            field=models.CharField(blank=True, choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=7, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=7, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(default='No name', max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=7, null=True, verbose_name='Пол'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='ElemOfTimetable',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
        migrations.AddField(
            model_name='studysession',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='attending',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='attending',
            name='studySession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StudySession', verbose_name='Занятие'),
        ),
        migrations.AddField(
            model_name='union',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Logo', verbose_name='Лого'),
        ),
    ]
