# Generated by Django 3.0.4 on 2020-04-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200403_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableelem',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Group', verbose_name='Группа'),
        ),
    ]
