# Generated by Django 3.0.4 on 2020-04-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_timetableelem_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableelem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group', verbose_name='Группа'),
        ),
    ]
