# Generated by Django 3.0.4 on 2020-04-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200403_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableelem',
            name='beginTimeStr',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='cancelReason',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Причина отмены'),
        ),
    ]
