# Generated by Django 3.0.4 on 2020-04-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200403_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableelem',
            name='endTime',
            field=models.TimeField(blank=True, default='00:00:00', verbose_name='Время конца'),
        ),
        migrations.AlterField(
            model_name='timetableelem',
            name='beginTimeStr',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
