# Generated by Django 3.0.4 on 2020-04-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200404_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableelem',
            name='beginTimeStr',
        ),
        migrations.AddField(
            model_name='user',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Union', verbose_name='Объединение'),
        ),
    ]
