# Generated by Django 3.0.4 on 2020-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200410_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileIcon',
            field=models.ImageField(blank=True, null=True, upload_to='profileIcon', verbose_name='Фото профиля'),
        ),
    ]
