# Generated by Django 3.0.6 on 2020-05-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_profileicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='worktime',
        ),
        migrations.AddField(
            model_name='studysession',
            name='teacherAttended',
            field=models.BooleanField(blank=True, default=True, verbose_name='Педагог был на занятии'),
        ),
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='main.Group', verbose_name='Ученики'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='childs', to='main.Parent', verbose_name='Родители'),
        ),
    ]
