# Generated by Django 3.0.7 on 2020-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200519_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(default='Иван', max_length=16, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(default='Иванов', max_length=16, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='patronymic',
            field=models.CharField(blank=True, default='Иванович', max_length=16, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Иван', max_length=16, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Иванов', max_length=16, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, default='Иванович', max_length=16, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, default='Иванович', max_length=16, null=True, verbose_name='Отчество'),
        ),
    ]
