# Generated by Django 3.0.7 on 2020-06-18 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200519_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='createdAt',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='student',
            name='createdAt',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(default='Иван', max_length=16, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(default='Иванов', max_length=16, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='patronymic',
            field=models.CharField(blank=True, default='Иванович', max_length=16, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Иван', max_length=16, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Иванов', max_length=16, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, default='Иванович', max_length=16, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, default='Иванович', max_length=16, null=True, verbose_name='Отчество'),
        ),
    ]
