# Generated by Django 3.0.7 on 2020-06-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200618_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='createdAt',
            field=models.DateField(blank=True, default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='student',
            name='createdAt',
            field=models.DateField(blank=True, default='2020-01-01'),
        ),
    ]
