# Generated by Django 3.0.7 on 2020-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200618_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
