# Generated by Django 3.0.7 on 2020-06-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200618_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='isDeleted',
        ),
        migrations.AddField(
            model_name='parent',
            name='isArchived',
            field=models.BooleanField(blank=True, default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='student',
            name='isArchived',
            field=models.BooleanField(blank=True, default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='user',
            name='isArchived',
            field=models.BooleanField(blank=True, default=False, verbose_name='В архиве'),
        ),
    ]
